/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AnalysisRecord = IDL.Record({
  'trend' : IDL.Text,
  'timeframe' : IDL.Text,
  'resistanceLevels' : IDL.Vec(IDL.Float64),
  'summary' : IDL.Text,
  'supportLevels' : IDL.Vec(IDL.Float64),
  'assetSymbol' : IDL.Text,
  'timestamp' : Time,
  'riskLevel' : IDL.Text,
  'rsiStatus' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAnalysisHistory' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAnalysis' : IDL.Func([AnalysisRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AnalysisRecord = IDL.Record({
    'trend' : IDL.Text,
    'timeframe' : IDL.Text,
    'resistanceLevels' : IDL.Vec(IDL.Float64),
    'summary' : IDL.Text,
    'supportLevels' : IDL.Vec(IDL.Float64),
    'assetSymbol' : IDL.Text,
    'timestamp' : Time,
    'riskLevel' : IDL.Text,
    'rsiStatus' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAnalysisHistory' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAnalysis' : IDL.Func([AnalysisRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };